# Data catalog

In this notebook, we'll explore all the data in Fidap. There are two key tables that contain the metadata -

 - ``meta_tables`` which contains details about the tables, and 
 - ``meta_fields`` which contains details about the fields

In [2]:
import pandas as pd
from fidap import fidap_client

#### Initiat the fidap_client

In [3]:
fidap = fidap_client(db="sf", api_key="1287a2d9e40042edb53254cd203b9a0b")

In [4]:
fidap.sql("select * from meta_tables")

                  NAME QUANDL_CODE   DISPLAY_NAME                                        DESCRIPTION      rows  COLS  DATAPOINTS
0         fundamentals         SF1   Fundamentals  Fundamentals data pulled from earnings stateme...    430420   113    48637460
1               events      EVENTS         Events              Corporate events from Form 8 filings.    484349     3     1453047
2  ticker_shareholders        SF3A        Holders   Institutional shareholders statistics by ticker.    366091    29    10616639
3           portfolios        SF3B     Portfolios                             13F portfolio summary.    135561    28     3795708
4              tickers     TICKERS        Tickers                              Master tickers table.      6078   209     1270302
5                sp500       SP500        S&P 500          Tickers that belong to the S&P 500 index.     10845     7       75915
6              actions     ACTIONS   Corp Actions         This table contains earnings fundamentals.    139329     7      975303
7                daily        None  Daily History                           Historical daily prices.  18042804    40   721712160
8                dates        None          Dates                 Calendar for the US equity market.      1278     3        3834
9                 corr        None   Correlations  Calculated correlations - top 100 for each stock.     43110     3      129330

If we wanted to drill down into any individual table, all we need to do is select the fields from that table, as below -

In [5]:
fidap.sql('select * from meta_fields where "table" = \'fundamentals\' limit 10')

          table          NAME                            DISPLAY_NAME  ... UNIQUENESS          MEAN       MEDIAN
0  fundamentals        ticker                           Ticker Symbol  ...   0.016756           NaN          NaN
1  fundamentals     dimension                               Dimension  ...   0.000014           NaN          NaN
2  fundamentals  calendardate                           Calendar Date  ...   0.000046           NaN          NaN
3  fundamentals       datekey                                Date Key  ...   0.003615           NaN          NaN
4  fundamentals  reportperiod                           Report Period  ...   0.001766           NaN          NaN
5  fundamentals   lastupdated                       Last Updated Date  ...   0.001185           NaN          NaN
6  fundamentals        accoci  Accumulated Other Comprehensive Income  ...   0.091696  2.276103e+08      -6000.0
7  fundamentals        assets                            Total Assets  ...   0.222871  1.681796e+11  801015000.0
8  fundamentals     assetsavg                          Average Assets  ...   0.238474  2.778233e+11  850420000.0
9  fundamentals       assetsc                          Current Assets  ...   0.170357  2.019411e+10  187843000.0

[10 rows x 9 columns]

Let's look at a few tables together. We will eventually add deep dives into each of the tables, but here's a quick look at some of the most important tables first.

## Tickers

The tickers table is generally the starting point for most analyses. This table contains all companies, both past and present, as well as a ton of information about them - including both pricing information as well as fundamentals.