# Data catalog

In this notebook, we'll explore all the data in Fidap. There are two key tables that contain the metadata -

 - ``meta_tables`` which contains details about the tables, and 
 - ``meta_fields`` which contains details about the fields

In [1]:
import pandas as pd
from fidap import fidap_client
import config

#### Initiat the fidap_client

In [2]:
fidap = fidap_client(api_key=config.FIDAP_API_KEY)

In [3]:
fidap.sql("select * from meta_tables")

,table_catalog,table_schema,table_name,row_count,bytes,column_count,datapoints,description
0,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,ACTIONS,139329.0,1.440256e+06,7,975303.0,N.A update if required
1,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,CENSUSDATA,298080.0,1.022106e+07,17,5067360.0,N.A update if required
2,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,CORR,43110.0,4.725760e+05,3,129330.0,N.A update if required
3,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,CRYPTODATA,4708.0,2.769920e+05,13,61204.0,N.A update if required
4,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,DAILY,18042804.0,2.329843e+09,40,721712160.0,N.A update if required
5,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,DATES,1278.0,1.792000e+04,3,3834.0,N.A update if required
6,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,EVENTS,484349.0,2.043392e+06,3,1453047.0,N.A update if required
7,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,FIDAP_PEOPLEDATALABS,NaN,NaN,11,NaN,N.A update if required
8,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,FUNDAMENTALS,430420.0,1.555558e+08,113,48637460.0,N.A update if required
9,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,INSIDER_TRADES,7223907.0,2.408422e+08,24,173373768.0,N.A update if required
10,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,META_FIELDS,803.0,7.270400e+04,31,24893.0,N.A update if required
11,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,META_TABLES,25.0,2.048000e+03,8,200.0,N.A update if required
12,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,META_TABLES_VIEW,NaN,NaN,8,NaN,N.A update if required
13,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,PEOPLE_DATA_LABS,1794662.0,2.816251e+08,17,30509254.0,N.A update if required
14,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,PORTFOLIOS,135561.0,8.631296e+06,28,3795708.0,N.A update if required
15,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,PORTFOLIO_DETAILS,35948220.0,4.166953e+08,7,251637540.0,N.A update if required
16,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,RAW_PEOPLEDATALABS,8567134.0,3.228022e+09,1,8567134.0,N.A update if required
17,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,SP500,10604.0,3.788800e+04,7,74228.0,N.A update if required
18,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,TICKERS,6078.0,5.461504e+06,209,1270302.0,N.A update if required
19,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,TICKER_SHAREHOLDERS,366091.0,2.130944e+07,29,10616639.0,N.A update if required
20,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,WALLSTREETBETS_WEEKLY_TOP,9.0,1.024000e+03,4,36.0,N.A update if required
21,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,WIKIDATA_COMPANIES,6282.0,2.114560e+05,14,87948.0,N.A update if required

If we wanted to drill down into any individual table, all we need to do is select the fields from that table, as below -

In [6]:
fidap.sql('select * from meta_fields where table_name = \'FUNDAMENTALS\' limit 10')

,table_name,database_name,schema_name,column_name,count,distinct_count,distinct_count_with_nan,distinct_count_without_nan,freq,max,...,sum,type,variance,table,indicator,isfilter,isprimarykey,title,description,unittype
0,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,ACCOCI,425239,39468,39469,39468,NaN,8.380761e+12,...,9.678876e+13,Variable.TYPE_NUM,2.092612e+21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,ASSETS,425222,95928,95929,95928,NaN,5.524196e+14,...,7.151366e+16,Variable.TYPE_NUM,3.719295e+25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,ASSETSAVG,227911,102644,102645,102644,NaN,5.060100e+14,...,6.331898e+16,Variable.TYPE_NUM,6.390429e+25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,ASSETSC,337341,73325,73326,73325,NaN,4.770100e+13,...,6.812302e+15,Variable.TYPE_NUM,3.579971e+23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,ASSETSNC,337341,71622,71623,71622,NaN,1.941400e+14,...,1.733584e+16,Variable.TYPE_NUM,3.706201e+24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,ASSETTURNOVER,226615,4589,4590,4589,NaN,2.371289e+03,...,1.747139e+05,Variable.TYPE_NUM,1.661730e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,BVPS,423900,48474,48475,48474,NaN,7.889255e+07,...,-1.135511e+09,Variable.TYPE_NUM,2.595433e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,CALENDARDATE,430420,20,20,20,33554.0,NaN,...,NaN,Variable.TYPE_CAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,CAPEX,415610,86654,86655,86654,NaN,2.783104e+10,...,-1.529250e+15,Variable.TYPE_NUM,4.957278e+22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,FUNDAMENTALS,FIDAP_DATA_SOURCES,FIDAP_SCHEMA,CASHNEQ,425226,78942,78943,78942,NaN,7.854971e+13,...,7.157880e+15,Variable.TYPE_NUM,5.702567e+23,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Let's look at a few tables together. We will eventually add deep dives into each of the tables, but here's a quick look at some of the most important tables first.

## Tickers

The tickers table is generally the starting point for most analyses. This table contains all companies, both past and present, as well as a ton of information about them - including both pricing information as well as fundamentals.